parameters:
#    teststest.example.class: tests\testBundle\Example

services:
#    teststest.example:
#        class: %teststest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
